# Generated by Django 6.0.4 on 2026-04-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card')], max_length=30)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField()),
                ('service_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_notes', models.TextField()),
                ('labor_hours', models.IntegerField(default=0)),
                ('repair_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mechanic')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='PickupDropRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField(default='Silver Auto, Vatva, Ahmedabad')),
                ('pickup_time', models.DateTimeField()),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Picked Up', 'Picked Up'), ('Dropped', 'Dropped')], default='Scheduled', max_length=20)),
                ('vehicle_condition_notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicerequest')),
            ],
        ),
    ]
